# Generated by Django 4.2.2 on 2023-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonalish',
            name='aktiv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
